# Generated by Django 5.2.7 on 2026-03-25 15:30

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDocument",
            fields=[
                ("id", django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("password_hash", models.CharField(max_length=256)),
                ("role", models.CharField(db_index=True, max_length=40)),
                ("preferred_language", models.CharField(default="vi", max_length=5)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountSessionDocument",
            fields=[
                ("id", django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ("account_id", models.CharField(db_index=True, max_length=32)),
                ("token", models.CharField(max_length=120, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "account_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]

