from __future__ import annotations

from typing import Protocol

from modules.catalog.application.dto import ServicePackagePayload
from modules.catalog.domain.entities import ServicePackage


class ServicePackageRepository(Protocol):
    def list(self, *, featured_only: bool = False, active_only: bool = True) -> list[ServicePackage]: ...
    def get_by_slug(self, slug: str) -> ServicePackage | None: ...
    def create(self, payload: ServicePackagePayload) -> ServicePackage: ...
    def update(self, slug: str, payload: ServicePackagePayload) -> ServicePackage: ...
    def delete(self, slug: str) -> None: ...
