# Generated by Django 5.2.7 on 2026-03-21 19:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('service_slug', models.SlugField(max_length=120)),
                ('service_name', models.CharField(max_length=160)),
                ('launch_site_name', models.CharField(max_length=120)),
                ('flight_date', models.DateField()),
                ('flight_time', models.CharField(max_length=5)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=40)),
                ('payment_status', models.CharField(max_length=40)),
                ('approval_status', models.CharField(db_index=True, max_length=40)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('flight_status', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
