# Generated by Django 5.2.7 on 2026-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdocument',
            name='assigned_pilot_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bookingdocument',
            name='assigned_pilot_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
