# Generated by Django 5.2.7 on 2026-03-21 19:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactionDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=32, unique=True)),
                ('method', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_name', models.CharField(max_length=80)),
                ('provider_reference', models.CharField(max_length=120)),
                ('payment_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
