# Generated by Django 5.2.7 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactiondocument",
            name="deposit_percentage",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="paymenttransactiondocument",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttransactiondocument",
            name="qr_code_url",
            field=models.URLField(blank=True, default="https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=demo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttransactiondocument",
            name="transfer_content",
            field=models.CharField(blank=True, default="BKDEMO", max_length=160),
            preserve_default=False,
        ),
    ]
