# Generated by Django 5.2.7 on 2026-03-21 19:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDayDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('service_slug', models.SlugField(max_length=120)),
                ('date', models.DateField()),
                ('temperature_c', models.FloatField()),
                ('wind_kph', models.FloatField()),
                ('uv_index', models.PositiveIntegerField()),
                ('flight_condition', models.CharField(max_length=80)),
                ('slots', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'availability_days',
                'ordering': ['date'],
                'unique_together': {('service_slug', 'date')},
            },
        ),
    ]
