# Generated by Django 5.2.7 on 2026-03-24 13:59

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('cover_image', models.URLField()),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
