# Generated by Django 5.2.7 on 2026-03-21 19:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTrackingDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('service_name', models.CharField(max_length=160)),
                ('flight_status', models.CharField(max_length=40)),
                ('current_location', models.JSONField(default=dict)),
                ('route_points', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flight_tracking',
                'ordering': ['-updated_at'],
            },
        ),
    ]
