# Generated by Django 5.2.7 on 2026-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttrackingdocument',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
