# Generated by Django 5.2.7 on 2026-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_flighttrackingdocument_pilot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flighttrackingdocument",
            name="tracking_active",
            field=models.BooleanField(default=False),
        ),
    ]
