# Generated by Django 5.2.7 on 2026-03-21 19:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageDocument',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_duration_minutes', models.PositiveIntegerField()),
                ('included_services', models.JSONField(default=list)),
                ('participation_requirements', models.JSONField(default=list)),
                ('min_child_age', models.PositiveIntegerField(default=6)),
                ('hero_image', models.URLField()),
                ('gallery_images', models.JSONField(default=list)),
                ('launch_site_name', models.CharField(max_length=120)),
                ('launch_lat', models.FloatField()),
                ('launch_lng', models.FloatField()),
                ('landing_site_name', models.CharField(max_length=120)),
                ('landing_lat', models.FloatField()),
                ('landing_lng', models.FloatField()),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_packages',
                'ordering': ['-featured', 'price', 'name'],
            },
        ),
    ]
